### ISSUE TITLE
uniqueItemProperties is throwing TypeError: Cannot read property 'id' of null 

### ISSUE THREAD

**Issue by pushpa446** [epoberezkin/ajv-keywords#101]
When you pass `null` as an item in the array, `uniqueItemProperties` is throwing error.

**To reproduce:**
```
const Ajv = require("ajv");

const ajv = new Ajv({
  removeAdditional: false,
  useDefaults: true,
  coerceTypes: true,
  allErrors: true
});

require("ajv-keywords")(ajv, ["uniqueItemProperties"]);

const schema = {
  type: "object",
  properties: {
    vehicles: {
      type: "array",
      uniqueItemProperties: ["id"],
      items: {
        type: "object",
        properties: {
          id: {type: "string"},
          name: {type: "string"}
        }
      }
    }
  }
};

const validate = ajv.compile(schema);
const data = {
  vehicles: [{id: "123", name: "Bus"}, null]
};
const valid = validate(data);
if (!valid)console.log(validate.errors);

```
**Result**
```
~/node_modules/ajv-keywords/keywords/uniqueItemProperties.js:15
                if (typeof data[j] == 'object' && equal(data[i][key], data[j][key]))
                                                               ^

TypeError: Cannot read property 'id' of null
    at Ajv.<anonymous> (~/node_modules/ajv-keywords/keywords/uniqueItemProperties.js:15:64)
    at validate (eval at localCompile (~/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:2389)
    at Object.<anonymous> (~/testUniqueProperties.js:33:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
```

**Any workaround to mitigate the issue?**

**Comment by epoberezkin** [comment]
Has to be fixed to exclude null. The workaround would be to use allOf with 2 schemas and test for item types in the first, and for uniqueItemProperties in the 2nd.

**Comment by pushpa446** [comment]
Do you mean like below?
```
const schema = {
  type: "object",
  properties: {
    vehicles: {
      allOf: [
        {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: {type: "string"},
              name: {type: "string"}
            }
          }
        },
        { uniqueItemProperties: ["id"] }
      ]
    }
  }
};```

I'm still facing the issue.

**Comment by epoberezkin** [comment]
Yes. You’ll need to remove allErrors option... it has to be fixed - there is no nice workaround really
