### ISSUE TITLE
throw new Error('invalid "instanceof" keyword value ' + c);

### ISSUE THREAD

**Issue by john1jan** [epoberezkin/ajv-keywords#62]
```
Error: invalid "instanceof" keyword value Promise
    at getConstructor (node_modules/webpack/node_modules/ajv-keywords/keywords/instanceof.js:52:11)
    at Ajv.compile (node_modules/webpack/node_modules/ajv-keywords/keywords/instanceof.js:21:27)
    at Object.useCustomRule (node_modules/webpack/node_modules/ajv/lib/compile/index.js:275:26)
    at Object.generate_custom [as code] (node_modules/webpack/node_modules/ajv/lib/dotjs/custom.js:32:24)
    at Object.generate_validate [as validate] (node_modules/webpack/node_modules/ajv/lib/dotjs/validate.js:347:35)
```

**Comment by epoberezkin** [comment]
That can happen if you don’t have global Promise. Difficult to say more without knowing what you did.

**Comment by epoberezkin** [comment]
closing - please create a new issue with a minimal code sample if needed
